name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY }}
        run: .\publish.ps1
        shell: pwsh